
(function () {
    "use strict";

    // Add EDS content types to XboxJS.Data.ContentType if needed when calling MediaPlayer.setContentMetadata and passing in contentType
    // This code is commented out be default as most applications will just need the standard content types.  
    // Music, web video, or live TV apps may need additional content type values to support functionality
    // Note that these content types are just for in-app functionality and are not currently supported by XBL services such as Search
    // Related docs: https://developer.xboxlive.com/en-us/apps/development/documentation/adk/Pages/EDSTables_oct14.aspx

    // For Live TV - tvChannel content type
    // XboxJS.Data.ContentType.tvChannel = "tvChannel";

    // For Music
    //XboxJS.Data.ContentType.album = "album";
    //XboxJS.Data.ContentType.track = "musicVideo";
    //XboxJS.Data.ContentType.musicArtist = "musicArtist";

    // For Web Video
    //XboxJS.Data.ContentType.webVideo = "webVideo";
    //XboxJS.Data.ContentType.webVideoCollection = "webVideoCollection";


    // TODO: Replace the data with your real data.
    // You can add data from asynchronous sources whenever it becomes available. 
    var sampleMovieData = [
        { contentId: "abcd1234", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 1", season: 1, episode: 1, image: "/images/movieposter.png", url: "http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1235", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 2", season: 1, episode: 2, image: "/images/movieposter.png", url: "http://gslb.bestvcdn.com.cloudcdn.net/218.77.90.58/gslb/program/Dbackct_bestvcdn_comD/_wogP000iG6_/FDN/FDNB1664649/prime.m3u8?_mdCode=9674414&_cdnCode=BTV&_type=0&_rCode=TerOut_21562&_userId=023513000031081&_categoryCode=SMG_OTT_TV_JT&_categoryPath=SMG_OTT_TV,SMG_OTT_TV_JT,&_adPositionId=01001000&_adCategorySource=0&_flag=.m3u8&_enCode=m3u8&_cms=ctv&_service=b2c&_cp=1&_back=FASTWEB&_BitRate=700,1300,2300,4000&taskID=pb02.idc.xbox.bestv.com.cn_14301850139636298&_client=104", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1236", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 3", season: 1, episode: 3, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1237", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 4", season: 1, episode: 4, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1238", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 5", season: 1, episode: 5, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1239", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 6", season: 1, episode: 6, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1240", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 7", season: 2, episode: 7, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1241", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 8", season: 2, episode: 8, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1242", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 9", season: 2, episode: 9, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1243", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 10", season: 2, episode: 10, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1244", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 11", season: 2, episode: 11, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1245", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 12", season: 3, episode: 12, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1246", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 13", season: 3, episode: 13, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1247", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 14", season: 3, episode: 14, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1248", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 15", season: 3, episode: 15, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1249", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 16", season: 3, episode: 16, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" },
        { contentId: "abcd1250", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 17", season: 3, episode: 17, image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2, releaseDate: "2008" }
    ];

    var sampleSeriesData = [
        { contentId: "abcd1251", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 1", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1252", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 2", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1253", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 3", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1254", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 4", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1255", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 5", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1256", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 6", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1257", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 7", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1258", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 8", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1259", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 9", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1260", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 10", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1261", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 11", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1262", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 12", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1263", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 13", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1264", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 14", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1265", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 15", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1266", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 16", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1267", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 17", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" },
        { contentId: "abcd1268", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 18", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, releaseDate: "2008 - 2011" }
    ];

    var sampleSeasonData = [
        { contentId: "abcd1269", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.tvSeason, seasonNumber: 1, image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", episodes: 3, imageWidth: 1, imageHeight: 2 },
        { contentId: "abcd1270", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.tvSeason, seasonNumber: 2, image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", episodes: 3, imageWidth: 1, imageHeight: 2 },
        { contentId: "abcd1271", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.tvSeason, seasonNumber: 3, image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", episodes: 3, imageWidth: 1, imageHeight: 2 }
    ];

    var sampleEpisodeData = [
        [
            { contentId: "abcd1272", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.tvEpisode, title: "Episode 1", duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 1, episode: 1, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd1273", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.tvEpisode, title: "Episode 2", duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 1, episode: 2, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd1274", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.tvEpisode, title: "Episode 3", duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 1, episode: 3, imageWidth: 1, imageHeight: 2 }
        ],
        [
            { contentId: "abcd1275", contentRating: "Microsoft:16", title: "Episode 1", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 1, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd1276", contentRating: "Microsoft:16", title: "Episode 2", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 2, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd1277", contentRating: "Microsoft:16", title: "Episode 3", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 3, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd1278", contentRating: "Microsoft:16", title: "Episode 4", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 1, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd1279", contentRating: "Microsoft:16", title: "Episode 5", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 2, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd12710", contentRating: "Microsoft:16", title: "Episode 6", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 3, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd12711", contentRating: "Microsoft:16", title: "Episode 7", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 1, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd12712", contentRating: "Microsoft:16", title: "Episode 8", contentType: XboxJS.Data.ContentType.tvEpisode, dduration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 2, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd12713", contentRating: "Microsoft:16", title: "Episode 9", contentType: XboxJS.Data.ContentType.tvEpisode, desduration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 3, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd12714", contentRating: "Microsoft:16", title: "Episode 10", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 1, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd12715", contentRating: "Microsoft:16", title: "Episode 11", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 2, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd12716", contentRating: "Microsoft:16", title: "Episode 12", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 3, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd12717", contentRating: "Microsoft:16", title: "Episode 13", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 1, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd12718", contentRating: "Microsoft:16", title: "Episode 14", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 2, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd12719", contentRating: "Microsoft:16", title: "Episode 15", contentType: XboxJS.Data.ContentType.tvEpisode, duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 2, episode: 3, imageWidth: 1, imageHeight: 2 },
        ],
        [
            { contentId: "abcd1278", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.tvEpisode, title: "Episode 1", duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 3, episode: 1, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd1279", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.tvEpisode, title: "Episode 2", duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 3, episode: 2, imageWidth: 1, imageHeight: 2 },
            { contentId: "abcd1280", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.tvEpisode, title: "Episode 3", duration: 48, image: "/images/tvshow.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", season: 3, episode: 3, imageWidth: 1, imageHeight: 2 }
        ]
    ];

    var relatedTestData = {
        abcd1234: sampleMovieData,
        abcd1235: sampleMovieData,
        abcd1236: sampleMovieData,
        abcd1237: sampleMovieData,
        abcd1238: sampleMovieData,
        abcd1239: sampleMovieData,
        abcd1240: sampleMovieData,
        abcd1241: sampleMovieData,
        abcd1242: sampleMovieData,
        abcd1243: sampleMovieData,
        abcd1244: sampleMovieData,
        abcd1245: sampleMovieData,
        abcd1246: sampleMovieData,
        abcd1247: sampleMovieData,
        abcd1248: sampleMovieData,
        abcd1249: sampleMovieData,
        abcd1250: sampleMovieData
    };

    var sampleMovieSearchData = [
        { contentId: "abcd1234", title: "Movie 1", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1235", title: "Movie 2", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "R", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1236", title: "Movie 3", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "PG-13", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1237", title: "Movie 4", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "PG-13", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1238", title: "Movie 5", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "PG", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1239", title: "Movie 6", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "G", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1240", title: "Movie 7", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "PG", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1241", title: "Movie 8", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "PG-13", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1242", title: "Movie 9", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1243", title: "Movie 10", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1244", title: "Movie 11", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1245", title: "Movie 12", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "R", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1246", title: "Movie 13", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "R", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1247", title: "Movie 14", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "R", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1248", title: "Movie 15", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "R", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1249", title: "Movie 16", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "R", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
        { contentId: "abcd1250", title: "Movie 17", image: "/images/movieposter.png", url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "90 min", contentRating: "R", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.movie, releaseDate: "2008" },
    ];

    var sampleSeriesSearchData = [
        { contentId: "abcd1234", title: "Series 1", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.tvSeries },
        { contentId: "abcd1234", title: "Series 2", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.tvSeries },
        { contentId: "abcd1234", title: "Series 3", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.tvSeries },
        { contentId: "abcd1234", title: "Series 4", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", seasons: 3, contentRating: "Microsoft:16", imageWidth: 1, imageHeight: 2, contentType: XboxJS.Data.ContentType.tvSeries }
    ];

    var queueData = [
        { contentId: "abcd1249", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 16", image: "/images/movieposter.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2 },
        { contentId: "abcd1250", contentRating: "Microsoft:16", contentType: XboxJS.Data.ContentType.movie, title: "Movie 17", image: "/images/movieposter.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", length: "5 min", imageWidth: 1, imageHeight: 2 },
        { contentId: "abcd1251", contentRating: "unrated", contentType: XboxJS.Data.ContentType.tvSeries, title: "Series 1", image: "/images/tvshow.png", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas mauris lorem, iaculis rhoncus volutpat vel, tristique ut sapien.", imageWidth: 1, imageHeight: 2 },
    ];

    var publicMembers = {
        MovieData: sampleMovieData,
        SeriesData: sampleSeriesData,
        SeasonData: sampleSeasonData,
        EpisodeData: sampleEpisodeData,
        RelatedData: relatedTestData,
        MovieSearchResults: sampleMovieSearchData,
        SeriesSearchResults: sampleSeriesSearchData,
        QueueData: queueData
    };

    WinJS.Namespace.define("MyApp", publicMembers);

})();